# Generated by Django 3.2.5 on 2021-07-05 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0002_auto_20210705_0556'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentDiskUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='viewer.document')),
            ],
        ),
    ]
